hsp = 0; //horizontal speed
vsp = 0; //vertical speed
grv = 0.6; //gravity
jumpheight = -7;
walkspd = 3; //walk speed
healthpoints = 400;
flash = 3;
RES = 15;
BUFF = 0;
ATK = 5;
DEF = 3;
lightiframes = 0; //prevents multiple hits registering too fast
heavyiframes = 0;
magicdamagedealt = 0;
attackcd = 30;